### ISSUE TITLE
[Bug]: 按照“本地开发环境搭建”无法成功运行cmdb-api

### ISSUE THREAD

**Issue by abelit** [veops/cmdb#533]
### This bug is related to UI or API?

API

### What happened?

Loading .env environment variables...
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'autoapp', an ImportError was raised:

Traceback (most recent call last):
  File "/home/abelit/.local/share/virtualenvs/cmdb-api-lqIxm16l/lib/python3.8/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/home/abelit/Downloads/cmdb/cmdb-api/autoapp.py", line 5, in <module>
    from api.app import create_app
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/app.py", line 21, in <module>
    import api.views.entry
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/views/entry.py", line 25, in <module>
    register_resources(os.path.join(HERE, "cmdb"), rest)
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/resource.py", line 40, in register_resources
    view = __import__(os.path.splitext(filename)[0])
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/views/cmdb/auto_discovery.py", line 11, in <module>
    from api.lib.cmdb.auto_discovery.auto_discovery import AutoDiscoveryCICRUD
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/lib/cmdb/auto_discovery/auto_discovery.py", line 10, in <module>
    from api.lib.cmdb.ci import CIManager
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/lib/cmdb/ci.py", line 20, in <module>
    from api.lib.cmdb.ci_type import CITypeAttributeManager
  File "/home/abelit/Downloads/cmdb/cmdb-api/api/lib/cmdb/ci_type.py", line 38, in <module>
    from api.models.cmdb import AutoDiscoveryCITypeRelation
ImportError: cannot import name 'AutoDiscoveryCITypeRelation' from 'api.models.cmdb' (/home/abelit/Downloads/cmdb/cmdb-api/api/models/cmdb.py)

另一个错误是： python 3.8以“import imp"报错找不到imp模块，模块名已经是importlib了

### Version

newest

**Comment by pycook** [comment]
用release的代码
