### ISSUE TITLE
ModuleNotFoundError: No module named 'attribute'

### ISSUE THREAD

**Issue by xhongc** [veops/cmdb#68]
你好，
首先感谢你提供了优秀的源码，对我很有帮助
我在使用pycharm 运行flask 是 报错
Traceback (most recent call last):
  File "C:\Users\Administrator\Envs\flask_cmdb\lib\site-packages\flask\cli.py", line 236, in locate_app
    __import__(module_name)
  File "E:\charles\coding\cmdb\cmdb-api\autoapp.py", line 7, in <module>
    from api.app import create_app
  File "E:\charles\coding\cmdb\cmdb-api\api\app.py", line 15, in <module>
    import api.views
  File "E:\charles\coding\cmdb\cmdb-api\api\views\__init__.py", line 23, in <module>
    register_resources(os.path.join(HERE, "cmdb"), rest)
  File "E:\charles\coding\cmdb\cmdb-api\api\resource.py", line 35, in register_resources
    view = __import__(os.path.splitext(filename)[0])
ModuleNotFoundError: No module named 'attribute'

而在终端窗口运行不会报错，你知道是什么原因吗？

**Comment by pycook** [comment]
新版本应该不会有这个问题
